### ISSUE TITLE
Set up Java Spring Boot project for backend

### ISSUE THREAD

**Issue by jacobg431** [jacobg431/create-a-cv-backend#1]
Create Java Spring Boot project with necessary dependencies using Maven.

**Comment by shubhampawar13** [comment]
If you want to create it fast,
Step1] Go to Spring Initializr website--> https://start.spring.io/ ,
Step2]  Select, Project as maven , your Spring boot version, and fill Project metadata info and starter dependencies whichever you want to use .
Step3] Download this file from the website extract it and import it in Eclipse.
And you are good to go.

**Comment by jacobg431** [comment]
Thank you for the tip, @shubhampawar13 ! This is our first Spring Boot project, and we are currently looking into how to set up the project properly. Feel free to follow along while we develop the web app.
